# Generated by Django 4.2.5 on 2023-09-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_manufacturing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Manufacturing_Time',
            field=models.CharField(max_length=122),
        ),
    ]
